---
name: Green Metrics Sustainable Computing Experiment
author: Student
description: >
  A simple controlled CPU workload used to demonstrate
  energy and environmental measurement using the Green Metrics Tool.

services:
  workload:
    image: alpine
    setup-commands:
      - command: apk add --no-cache stress-ng

flow:
  - name: CPU Workload
    container: workload
    commands:
      - type: console
        command: stress-ng --cpu 1 --timeout 10s --quiet
        note: Running controlled CPU workload
